[cygno-ro]
type = s3
provider = Ceph
endpoint = https://s3.cr.cnaf.infn.it:7480
env_auth = false
anonymous = true
read_only = true
list_version = 2

[mnv-data]
type = alias
remote = cygno-ro:cygno:cygno-data/NMV/
